/*
 * generated by Xtext 2.24.0
 */
package org.dataflowanalysis.pcm.extension.dddsl.scoping;

import org.dataflowanalysis.pcm.extension.dddsl.scoping.AbstractDDDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping on how and when
 * to use it.
 */
public class DDDslScopeProvider extends AbstractDDDslScopeProvider {

}
