/*
 * generated by Xtext 2.30.0
 */
package org.dataflowanalysis.pcm.extension.dictionary.characterized.dsl.ide;


/**
 * Use this class to register ide components.
 */
public class CharacterizedDataDictionaryIdeModule extends AbstractCharacterizedDataDictionaryIdeModule {
}
