/*
 * generated by Xtext 2.30.0
 */
package org.dataflowanalysis.pcm.extension.dictionary.characterized.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.dataflowanalysis.pcm.extension.dictionary.characterized.dsl.CharacterizedDataDictionaryRuntimeModule;
import org.dataflowanalysis.pcm.extension.dictionary.characterized.dsl.CharacterizedDataDictionaryStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CharacterizedDataDictionaryIdeSetup extends CharacterizedDataDictionaryStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CharacterizedDataDictionaryRuntimeModule(), new CharacterizedDataDictionaryIdeModule()));
	}
	
}
