/*
 * generated by Xtext 2.30.0
 */
package org.dataflowanalysis.pcm.extension.dddsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.dataflowanalysis.pcm.extension.dddsl.DDDslRuntimeModule;
import org.dataflowanalysis.pcm.extension.dddsl.DDDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DDDslIdeSetup extends DDDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DDDslRuntimeModule(), new DDDslIdeModule()));
	}
	
}
