/*
 * generated by Xtext 2.30.0
 */
package org.dataflowanalysis.pcm.extension.dddsl.ide;


/**
 * Use this class to register ide components.
 */
public class DDDslIdeModule extends AbstractDDDslIdeModule {
}
