<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="nodeCharacteristics" nsURI="http://www.example.org/nodeCharacteristics"
    nsPrefix="nodeCharacteristics">
  <eClassifiers xsi:type="ecore:EClass" name="UsageAsignee" eSuperTypes="#//AbstractAssignee">
    <eStructuralFeatures xsi:type="ecore:EReference" name="usagescenario" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//usagemodel/UsageScenario"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RessourceAssignee" eSuperTypes="#//AbstractAssignee">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceenvironment" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/ResourceEnvironment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssemblyAssignee" eSuperTypes="#//AbstractAssignee">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assemblycontext" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//core/composition/AssemblyContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractAssignee" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignment" lowerBound="1"
        eType="#//AbstractAssignment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractAssignment" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="characteristics" upperBound="-1"
        eType="ecore:EClass ../../org.palladiosimulator.dataflow.dictionary.characterized/model/DataDictionaryCharacterized.ecore#//expressions/EnumCharacteristicReference"/>
  </eClassifiers>
</ecore:EPackage>
