/*
 * generated by Xtext 2.30.0
 */
package org.dataflowanalysis.pcm.extension.dddsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DDDslUiModule extends AbstractDDDslUiModule {

	public DDDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
