/*
 * generated by Xtext 2.24.0
 */
package org.dataflowanalysis.pcm.extension.dddsl;

import org.dataflowanalysis.pcm.extension.dddsl.DDDslStandaloneSetupGenerated;
import org.eclipse.emf.ecore.EPackage;
import org.dataflowanalysis.pcm.extension.model.confidentiality.behaviour.BehaviourPackage;
import org.dataflowanalysis.pcm.extension.model.confidentiality.dictionary.DictionaryPackage;
import org.palladiosimulator.pcm.core.CorePackage;
import org.palladiosimulator.pcm.parameter.ParameterPackage;

import com.google.inject.Injector;

import de.uka.ipd.sdq.stoex.StoexPackage;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DDDslStandaloneSetup extends DDDslStandaloneSetupGenerated {

    public static void doSetup() {
        new DDDslStandaloneSetup().createInjectorAndDoEMFRegistration();
    }

    @Override
    public void register(Injector injector) {
        super.register(injector);
        register(DictionaryPackage.eINSTANCE);
        register(BehaviourPackage.eINSTANCE);
        register(StoexPackage.eINSTANCE);
        register(ParameterPackage.eINSTANCE);
        register(CorePackage.eINSTANCE);
    }

    protected static void register(EPackage pkg) {
        EPackage.Registry.INSTANCE.putIfAbsent(pkg.getNsURI(), pkg);
    }

}
